name: Release to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Run linting
        run: npm run lint
      
      - name: Build package
        run: npm run build
      
      - name: Publish to npm
        run: |
          echo "Publishing to npm registry..."
          npm config set registry https://registry.npmjs.org/
          npm config set @railpath:registry https://registry.npmjs.org/
          npm publish --provenance
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 @railpath/finance-toolkit ${{ github.ref_name }}
            
            ### 📦 Installation
            ```bash
            npm install @railpath/finance-toolkit@${{ github.ref_name }}
            ```
            
            ### 🔗 Links
            - 📦 [npm Package](https://www.npmjs.com/package/@railpath/finance-toolkit)
            - 📖 [Documentation](https://github.com/railpath/finance-toolkit#readme)
            - 🐛 [Report Issues](https://github.com/railpath/finance-toolkit/issues)
          draft: false
          prerelease: false
